### PR TITLE
feat: admin can update user's organization

### PR DESCRIPTION
**Pull request by oranges-eating**
demo:http://www.killerwing.xyz:8000/
admin/123
Signed-off-by: killer <1533063601@qq.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@oranges-eating plz avoid the user itself from changing his own organization

**Comment by oranges-eating** [comment]
> @oranges-eating plz 避​​免用户自己改变自己的组织

Now users cannot choose their own organization in their profile

**Comment by hsluoyz** [comment]
@oranges-eating but they can call API to change it, right?

**Comment by oranges-eating** [comment]
> @oranges-eating but they can call API to change it, right?


They can’t use the API to change their organization and will return 403

**Pull request merged**
