### PR TITLE
fix:  table errors in frontend

### LINKED ISSUE #210: Duplicate key cause table errors
https://user-images.githubusercontent.com/24910914/127731784-a619ee85-2695-41a0-8347-58ac379e42a9.mp4

**All key-based components may occur this problem.**

This error cause we use the wrong or duplicate `rowKey` to build a table, every time we click the `Add` button, it generates a row like

```json
{
    "key": "Please select a signup item",
    "value": "..."
}
```

I fixed part of the errors in `web/src/UrlTable.js`: [`860fe91`](https://github.com/casbin/casdoor/commit/860fe91725865f202c2e282fe956647a6d4674f8#diff-aa513e39552689c307c054b430526e17ef206f1db173d3cb4c3705ee20d3d1abL98-R98)

### PR DESCRIPTION
**Pull request by WindSpiritSR**
1. fix #210 
2. Support case insensitivity search for SelectRegionBox
Deployed at: https://door.leviatan.cn/

Signed-off-by: WindSpiritSR <simon343riley@gmail.com>

### CODE REVIEW

**Comment by sh1luo** [comment]
@WindSpiritSR plz resolved conflict.

**Comment by WindSpiritSR** [comment]
@sh1luo fixed

**Comment by hsluoyz** [comment]
@WindSpiritSR the demo still doesn't work: https://door.leviatan.cn/organizations/built-in

image

**Comment by WindSpiritSR** [comment]
@hsluoyz deployed

**Comment by hsluoyz** [comment]
@Kininaru @sh1luo plz review

**Review by Kininaru — APPROVED** [review]
LGTM

**Pull request merged**
