### PR TITLE
Customized OAuth provider login URL

### PR DESCRIPTION
**Pull request by Kininaru**
Deployed at: https://door.chromium.link

Admin can modify the OAuth jump url for each OAuth Provider: 
image

And for every provider, admin can add some other properties: 
image

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Kininaru plz fix the wrong commits.

**Comment by Kininaru** [comment]
@hsluoyz Fixed.

**Comment by Kininaru** [comment]
@hsluoyz plz review

**Comment by hsluoyz** [comment]
The dangerous area is still not good looking. The table style is also not consistent with others. Closed for now.

image

image

**Pull request closed without merging**
