### PR TITLE
feat: add password Item forcibly

### PR DESCRIPTION
**Pull request by sh1luo**
Signed-off-by: wasabi <690898835@qq.com>

### CODE REVIEW

**Comment by sh1luo** [comment]
replace by: #132

**Comment by sh1luo** [comment]
demo link: http://test.rescld.cn/applications/app-built-in

- add password signup-Item forcibly when enabled password
- set password Item can not be deleted

**Comment by hsluoyz** [comment]
@Kininaru plz review.

**Review by Kininaru — COMMENTED** [review]
`this.updateApplicationField` called `this.setState`, which is an async function. This means that
 `this.state.application.enablePassword` is not promised to be updated immediately. 

But you called `this.checkIfHasPasswd` immediately. This means that `this.state.application.enablePassword` may not updated yet when you use it in the if statement in `this.checkIfHasPasswd`.

**Comment by sh1luo** [comment]
thanks,I will fix it.

**Review by Kininaru — APPROVED** [review]

**Comment by sh1luo** [comment]
done

**Comment by sh1luo** [comment]
@hsluoyz Why not merge it, is there a problem❓

**Pull request closed without merging**
