### PR TITLE
fix: improve i18n and add some translation

### PR DESCRIPTION
**Pull request by turbodog03**
Fix: #108 

Signed-off-by: turbodog <turbodog1003@gmail.com>

## code changes:
* I found some blocks like "token:Application", but there're no "token" section in en.json or zh.json files. so I edited them to be like "general:Application", and add their translation into the two .json files.
* I merged all statements in the two .json files that include "code" into one section named "code".

### CODE REVIEW

**Comment by turbodog03** [comment]
issue #108

**Comment by Zxilly** [comment]
@turbodog03 you should use `feat` action like: `feat: improve i18n and add some translation`

And you can use `resolve` or `fix` to link issue, like `resolve: #108`

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by turbodog03** [comment]
> @turbodog03 you should use `feat` action like: `feat: improve i18n and add some translation`
> 
> And you can use `resolve` or `fix` to link issue, like `resolve: #108`

thank you for your advice! I'll improve it right now.

**Comment by turbodog03** [comment]
resolve: #108

**Comment by hsluoyz** [comment]
@Kininaru

**Review by Kininaru — COMMENTED** [review]
Please do not change the code format.

**Comment by hsluoyz** [comment]
@turbodog03 plz provide online demo link for this PR and future PRs.

**Comment by turbodog03** [comment]
> @turbodog03 plz provide online demo link for this PR and future PRs.

Deployed at http://39.107.249.203/

**Comment by hsluoyz** [comment]
@Kininaru plz review.

**Review by Kininaru — APPROVED** [review]

**Pull request merged**
