### PR TITLE
fix: Using Crowdin action implement translation sync

### PR DESCRIPTION
**Pull request by ErikQQY**
Signed-off-by: ErikQQY <2283984853@qq.com>

### CODE REVIEW

**Comment by ErikQQY** [comment]
Demo repo: https://github.com/ErikQQY/qqydoor
Demo Crowdin project: https://crowdin.com/project/qqydoor

Every time an commit is pushed to the original repo and trigger the github action, if there are newly added translation in Crowdin, this action will use a new branch to propose a PR.

**Comment by ErikQQY** [comment]
@hsluoyz Plz review

**Comment by hsluoyz** [comment]
@ErikQQY I have cleaned the history to remove the wrong translation commits. Plz rebase the PR to keep only your commit in this PR:

image

**Comment by hsluoyz** [comment]
@ErikQQY this PR is replaced by commit: https://github.com/casbin/casdoor/commit/07178a7125db5083a7e32cb0dd194d30bbeb73c6

**Pull request merged**
