### PR TITLE
feat: Integrate Crowdin

### PR DESCRIPTION
**Pull request by ErikQQY**
Demo link: http://139.180.223.157:8000/

Everytime a commit is pushed to the master branch, it will trigger the Github action, if there are new translations on Crowdin, the action will upload and download the latest translations to ```web/src/locales/**``` in a new commit, if there are no new translations on Crowdin, nothing will happen.

A more detailed example is https://github.com/ErikQQY/qqydoor, after I commit to the repo, triggered the workflow, github action will sync the latest translations from Crowdin

Fix: #78 

Signed-off-by: ErikQQY <2283984853@qq.com>

### CODE REVIEW

**Comment by ErikQQY** [comment]
@hsluoyz Plz review

**Comment by hsluoyz** [comment]
@Kininaru plz review.

**Review by Kininaru — APPROVED** [review]

**Comment by hsluoyz** [comment]
@ErikQQY is there a CrowdIn link for your qqydoor: https://github.com/ErikQQY/qqydoor ?

**Comment by ErikQQY** [comment]
The Crowdin link is here

https://crowdin.com/project/qqydoor

**Pull request merged**
