### PR TITLE
feat: support i18n

### PR DESCRIPTION
**Pull request by RobotHuang**
fix: #13

### CODE REVIEW

**Comment by RobotHuang** [comment]
@hsluoyz plz review.

**Comment by hsluoyz** [comment]
@RobotHuang plz post some screenshots?

1. Set language widget
2. English UI
3. Chinese UI

**Comment by RobotHuang** [comment]
image
image
image
image
image
image
image
image
image

**Comment by hsluoyz** [comment]
lgtm

**Pull request merged**
