### PR TITLE
feat: support other mode,dingtalk,weibo,wechat,gitee,facebook

### PR DESCRIPTION
**Pull request by sh1luo**
Signed-off-by: wasabi <690898835@qq.com>

### CODE REVIEW

**Comment by sh1luo** [comment]
test demo url: http://test.rescld.cn/login/oauth/authorize?client_id=b4690f977fb0e2c609bf&response_type=code&redirect_uri=http://test.rescld.cn/callback&scope=read&state=casdoor

What needs special attention is,client_id and client_secrent are random

add Added support for 5 applications except github google qq
dingtalk,weibo,wechat,gitee,facebook

manage page: http://test.rescld.cn
account:admin
password:123

,where you can see their configuration。

**Comment by hsluoyz** [comment]
@sh1luo good work!

We plan to move all embedded SVG code into .svg files under Casbin static: https://github.com/casbin/static , in `/casdoor/buttons` path. For example, https://github.com/casbin/static/tree/master/casdoor/buttons/wechat.svg`, then we can use the CDN URL like: https://cdn.casbin.org/img/social_google.png

Can you do this?

**Comment by sh1luo** [comment]
How to accelerate the three components of github, facebook and google provided by `react-social-login-buttons`? Should I rewrite it?

**Comment by hsluoyz** [comment]
@sh1luo yes, see its source code, extract the svg out.

**Pull request merged**
