### PR TITLE
feat: add refresh token mechanism for server side

### PR DESCRIPTION
**Pull request by seriouszyx**
Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>

Fix: https://github.com/casbin/casdoor/issues/288

Fix: https://github.com/casbin/casdoor/issues/316

After researching, I draw up a flow chart for the refresh token mechanism of Casdoor as below. I have implemented the server-side and I will try the client-side. But before that, is there anything wrong with it? Welcome to discuss.

refresh_token流程图

### CODE REVIEW

**Comment by seriouszyx** [comment]
@hyperzlib plz review

**Review by sagilio — APPROVED** [review]
For OIDC, we may need support `offine_access` scope to control whether return the `refresh_token`.
spec: https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

**Comment by hsluoyz** [comment]
@seriouszyx sorry that it takes a little longer and today I found this PR has conflicts. Can you fix it so we can review and merge it?

image

**Comment by hsluoyz** [comment]
> LGTM. For OIDC, we may need support `offine_access` scope to control whether return the `refresh_token`. spec: https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

@seriouszyx can we support this?

**Comment by solo-xwz** [comment]
When will this version be released？

**Comment by seriouszyx** [comment]
@hsluoyz Conflicts have been resolved and the configuration UI of refresh token expire time has been added.

**Pull request merged**
